### ISSUE TITLE
package.json에 lint 의존성이 존재하지 않습니다.

### ISSUE THREAD

**Issue by wonkwangyeon** [luiseok/vue-template-twitch-ext#1]
현재 템플릿 init후 설정시 3개의 lint 항목을 설정 할 수 있는데,
template의 package.json에는 prettier만 존재하고 standard와 airbnb는 존재하지 않습니다.
확인부탁드립니다.

**Comment by luiseok** [comment]
Thanks

I Will fix as soon as possible.
